// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCadastro.Models;

namespace WebCadastro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("WebCadastro.Models.Cadastro", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(13)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("contato")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contato");

                    b.Property<DateTime>("datadeCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("datadeCriacao");

                    b.Property<string>("datadeNascimento")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("datadeNascimento");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("size");

                    b.HasKey("IdUsuario");

                    b.ToTable("Cadastro");
                });
#pragma warning restore 612, 618
        }
    }
}
